version: 2.1
defaults:
  docker_login: &docker_login
    run:
      name: Login to Dockerhub
      command: |
        if [ "${DOCKER_USER}" == "" ] || [ "${DOCKER_PASS}" == "" ]; then
            echo "Skipping Login to Dockerhub, no credentials."
        else
            echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin
        fi

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - DOCKERHUB
jobs:
  build:
    environment:
      DOCKER_USER: behoof4mind
      IMAGE_NAME: behoof4mind/devops-page
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - *docker_login
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker tag $IMAGE_NAME $IMAGE_NAME:$IMAGE_TAG
            docker tag $IMAGE_NAME $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest

